name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fish-actions/install-fish@v1
    - run: mkdir -p ~/.config/fish/completions
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: |
        dart pub get
        dart run > ~/.config/fish/completions/flutter.fish 
        dart test
    - uses: actions/upload-artifact@v1
      with:
        name: fish-completions
        path: ~/.config/fish/completions/flutter.fish
