name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fish-actions/install-fish@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: dart pub get
    - run: dart run > ~/.config/fish/completions/flutter.fish 
    - run: dart test
