name: release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: |
          dart pub get
          dart lib/main.dart > flutter.fish
      - uses: bruceadams/get-release@v1.2.3
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./flutter.fish
          asset_name: flutter.fish
          asset_content_type: text/plain
