name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          dart pub get
          dart lib/main.dart > flutter.fish 
          mkdir -p ~/.config/fish/completions
          cp flutter.fish ~/.config/fish/completions/
          dart test
      - uses: actions/upload-artifact@v4
        with:
          name: flutter.fish
          path: flutter.fish
